// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarenbuchungApi.Data;

#nullable disable

namespace WarenbuchungApi.Migrations
{
    [DbContext(typeof(WarenbuchungDbContext))]
    [Migration("20251125124845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WarenbuchungApi.Models.JustificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderIndex");

                    b.ToTable("JustificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 1,
                            Text = "Notfall-Entnahme für dringenden Auftrag"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 2,
                            Text = "Nachbestellung bereits veranlasst"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 3,
                            Text = "Lieferant bestätigt Nachschub"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 4,
                            Text = "Interne Umbuchung zwischen Standorten"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 5,
                            Text = "Qualitätsprüfung erforderlich"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 6,
                            Text = "Kundenspezifische Anpassung"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 7,
                            Text = "Wartungsarbeiten am Lager"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OrderIndex = 8,
                            Text = "Inventur-Korrektur"
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "PO-2025-001",
                            Status = "Offen",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "PO-2025-002",
                            Status = "Teilweise geliefert",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "PO-2025-003",
                            Status = "Offen",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "PO-2025-004",
                            Status = "Offen",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "PO-2025-005",
                            Status = "Abgeschlossen",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "ORD-001",
                            Status = "Offen",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "ORD-002",
                            Status = "Offen",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = "BEST-2025-100",
                            Status = "Offen",
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.OrderAssignedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DefaultQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderAssignedItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 1,
                            ProductId = 1,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 1,
                            ProductId = 3,
                            Unit = "BigBag"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 2,
                            ProductId = 21,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 4,
                            ProductId = 5,
                            Unit = "Platte"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 1,
                            ProductId = 10,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 2,
                            ProductId = 2,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 2,
                            ProductId = 16,
                            Unit = "Eimer"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 3,
                            ProductId = 4,
                            Unit = "Palette"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 3,
                            ProductId = 7,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 3,
                            ProductId = 22,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 4,
                            ProductId = 9,
                            Unit = "Stange"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 4,
                            ProductId = 17,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 5,
                            ProductId = 18,
                            Unit = "Set"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 5,
                            ProductId = 20,
                            Unit = "Eimer"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 5,
                            ProductId = 24,
                            Unit = "Trommel"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 6,
                            ProductId = 6,
                            Unit = "Rolle"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 6,
                            ProductId = 11,
                            Unit = "Stück"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 6,
                            ProductId = 23,
                            Unit = "Set"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 7,
                            ProductId = 8,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 7,
                            ProductId = 14,
                            Unit = "Stange"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 7,
                            ProductId = 21,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 8,
                            ProductId = 13,
                            Unit = "Bündel"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 5, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 8,
                            ProductId = 15,
                            Unit = "Rolle"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            OrderId = 8,
                            ProductId = 19,
                            Unit = "Kanister"
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultSupplier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("LocationStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hochwertiger Trockenbeton im 25kg Sack für Baustellenarbeiten",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Betonsack 25kg",
                            Price = 8.49m,
                            SKU = "MAT-BETON-25KG-001",
                            StockQuantity = 240,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard-Portlandzement für Maurer- und Betonarbeiten",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Zementsack 25kg",
                            Price = 7.95m,
                            SKU = "MAT-ZEMENT-25KG-001",
                            StockQuantity = 280,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gereinigter Bausand im 1 Tonnen BigBag für Beton- und Putzarbeiten",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Sand BigBag 1t",
                            Price = 52.50m,
                            SKU = "MAT-SAND-1T-001",
                            StockQuantity = 35,
                            Unit = "BigBag"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Palette mit 240 Hochlochziegeln für Mauerwerksbau",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Maurerziegel Palette",
                            Price = 329.00m,
                            SKU = "MAT-ZIEGEL-PAL-001",
                            StockQuantity = 18,
                            Unit = "Palette"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard-Gipskartonplatte 2500x1250x12,5 mm für Trockenbau",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Gipskartonplatte 12,5mm",
                            Price = 9.80m,
                            SKU = "MAT-GKP-125-001",
                            StockQuantity = 420,
                            Unit = "Platte"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mineralwolle-Rolle 100 mm, Wärmeleitgruppe 035",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Dämmstoffrolle Mineralwolle 100mm",
                            Price = 39.90m,
                            SKU = "MAT-DAEMM-100-001",
                            StockQuantity = 95,
                            Unit = "Rolle"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zementärer Estrich für Innen- und Außenbereich, 40kg Sack",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Estrich Fertigmischung 40kg",
                            Price = 11.20m,
                            SKU = "MAT-ESTRICH-40KG-001",
                            StockQuantity = 160,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gelöschter Kalk für Verputz- und Mauerarbeiten",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Kalkhydrat 25kg",
                            Price = 6.45m,
                            SKU = "MAT-KALK-25KG-001",
                            StockQuantity = 140,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bewehrungsstahlstäbe B500A, Länge 6 Meter, Durchmesser 12 mm",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Armierungsstahl B500 12mm",
                            Price = 14.75m,
                            SKU = "MAT-STAHL-12-001",
                            StockQuantity = 260,
                            Unit = "Stange"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paket mit 280 Tondachziegeln, passend für 12m² Dachfläche",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Dachziegel Paket",
                            Price = 489.00m,
                            SKU = "MAT-DACHZIEGEL-001",
                            StockQuantity = 22,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konstruktionsvollholz für Dach- und Gebäudekonstruktionen",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Holzbalken 60x120x4000",
                            Price = 29.40m,
                            SKU = "MAT-HOLZ-60X120-001",
                            StockQuantity = 180,
                            Unit = "Stück"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spanplatte P2 für Innenausbau, beidseitig fein geschliffen",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Spanplatte 18mm 2500x1250",
                            Price = 21.90m,
                            SKU = "MAT-SPAN-18-001",
                            StockQuantity = 210,
                            Unit = "Platte"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weichglühendes Kupferrohr, Bündel à 25 Meter, Durchmesser 15 mm",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Kupferrohr 15mm Bündel",
                            Price = 189.00m,
                            SKU = "MAT-KUPFER-15-001",
                            StockQuantity = 32,
                            Unit = "Bündel"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hart-PVC Rohr DN50, Länge 5m, für Abwasserinstallationen",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "PVC-Abflussrohr 50mm 5m",
                            Price = 17.60m,
                            SKU = "MAT-PVC-ROHR-50-001",
                            StockQuantity = 150,
                            Unit = "Stange"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MAG-Schweißdraht SG2, 0,8 mm Durchmesser, Rolle 5 kg",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Schweißdraht Rolle 5kg",
                            Price = 34.50m,
                            SKU = "MAT-SCHWEISS-5KG-001",
                            StockQuantity = 85,
                            Unit = "Rolle"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flex-Fugenmörtel 10kg Eimer, geeignet für Innen- und Außenbereich",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Fugenmasse 10kg",
                            Price = 18.75m,
                            SKU = "MAT-FUGEN-10KG-001",
                            StockQuantity = 95,
                            Unit = "Eimer"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flexibler Fliesenkleber für Keramik- und Feinsteinzeug",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Fliesenkleber Flex 25kg",
                            Price = 16.40m,
                            SKU = "MAT-FLIESEN-25KG-001",
                            StockQuantity = 190,
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Neutralvernetzendes Bau-Silikon, Set mit 6 Kartuschen à 310 ml",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Silikon Kartuschen Set 6x310ml",
                            Price = 27.90m,
                            SKU = "MAT-SILIKON-SET-001",
                            StockQuantity = 110,
                            Unit = "Set"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Haftgrundierung für mineralische und organische Putze, 10 Liter",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Putzgrund 10L",
                            Price = 24.60m,
                            SKU = "MAT-PUTZGRUND-10L-001",
                            StockQuantity = 75,
                            Unit = "Kanister"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dispersionsfarbe für Innenräume, hochdeckend, 15 Liter Eimer",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Innenfarbe Weiß 15L",
                            Price = 39.50m,
                            SKU = "MAT-INNENFARBE-15L-001",
                            StockQuantity = 65,
                            Unit = "Eimer"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paket mit 100 Stück Schrauben M6x20mm für Baustellen",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Schraubenpaket M6x20",
                            Price = 12.99m,
                            SKU = "MAT-SCHRAUBE-M6X20-001",
                            StockQuantity = 50,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paket mit 50 Stück Dübel 8mm für Wandmontage",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Dübelpaket 8mm",
                            Price = 8.99m,
                            SKU = "MAT-DUEBEL-8MM-001",
                            StockQuantity = 75,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set aus zwei Montagekleber-Kartuschen für starke Verklebungen",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Montagekleber Set 2x290ml",
                            Price = 15.99m,
                            SKU = "MAT-MONTAGEKLEBER-001",
                            StockQuantity = 30,
                            Unit = "Set"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Installationsleitung NYM-J 3x2,5 mm², Trommel mit 100 Metern",
                            ItemType = "Material",
                            LocationStock = 0m,
                            Name = "Elektrokabel NYM-J 3x2,5 100m",
                            Price = 89.99m,
                            SKU = "MAT-KABEL-NYM-3X25-001",
                            StockQuantity = 20,
                            Unit = "Trommel"
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.ProjectAssignedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DefaultQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProjectKey", "ProductId")
                        .IsUnique();

                    b.ToTable("ProjectAssignedItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 21,
                            ProjectKey = "PROJ-2025-001",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 1,
                            ProjectKey = "PROJ-2025-001",
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 23,
                            ProjectKey = "PROJ-2025-002",
                            Unit = "Set"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 20, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 10,
                            ProjectKey = "PROJ-2025-001",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 7,
                            ProjectKey = "PROJ-2025-002",
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 20, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 22,
                            ProjectKey = "PROJ-2025-002",
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 5,
                            ProjectKey = "PROJ-2025-003",
                            Unit = "Platte"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 12,
                            ProjectKey = "PROJ-2025-003",
                            Unit = "Platte"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 20, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 18,
                            ProjectKey = "PROJ-2025-003",
                            Unit = "Set"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 6,
                            ProjectKey = "PROJ-2025-004",
                            Unit = "Rolle"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 15,
                            ProjectKey = "PROJ-2025-004",
                            Unit = "Rolle"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 20, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 24,
                            ProjectKey = "PROJ-2025-004",
                            Unit = "Trommel"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 2,
                            ProjectKey = "PROJ-2025-005",
                            Unit = "Sack"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 10, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 9,
                            ProjectKey = "PROJ-2025-005",
                            Unit = "Stange"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 20, 0, 0, DateTimeKind.Utc),
                            DefaultQuantity = 0m,
                            ProductId = 20,
                            ProjectKey = "PROJ-2025-005",
                            Unit = "Eimer"
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "München, Deutschland",
                            ContactPerson = "Max Mustermann",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@lieferant-a.de",
                            Name = "Lieferant A",
                            Phone = "+49 89 123456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Berlin, Deutschland",
                            ContactPerson = "Anna Schmidt",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@lieferant-b.de",
                            Name = "Lieferant B",
                            Phone = "+49 30 654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hamburg, Deutschland",
                            ContactPerson = "Peter Weber",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@lieferant-c.de",
                            Name = "Lieferant C",
                            Phone = "+49 40 987654"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Köln, Deutschland",
                            ContactPerson = "Lisa Müller",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@lieferant-d.de",
                            Name = "Lieferant D",
                            Phone = "+49 221 111222"
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Locations")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsAdmin");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@warenbuchung.de",
                            FirstName = "Admin",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "User",
                            Locations = "Lagerort München, Lagerort Berlin, Lagerort Hamburg, Köln S04",
                            PasswordHash = "$2a$11$u/j1O2ujsjekqZj0iFpWLeNA3r88Nzztnkq4F1HTI8n3EnlqtHrcu",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@warenbuchung.de",
                            FirstName = "User",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "Eins",
                            Locations = "Lagerort München",
                            PasswordHash = "$2a$11$u/j1O2ujsjekqZj0iFpWLeNA3r88Nzztnkq4F1HTI8n3EnlqtHrcu",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@warenbuchung.de",
                            FirstName = "User",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "Zwei",
                            Locations = "Lagerort Berlin, Lagerort Hamburg",
                            PasswordHash = "$2a$11$u/j1O2ujsjekqZj0iFpWLeNA3r88Nzztnkq4F1HTI8n3EnlqtHrcu",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@warenbuchung.de",
                            FirstName = "Admin",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Eins",
                            Locations = "Lagerort München, Lagerort Berlin",
                            PasswordHash = "$2a$11$u/j1O2ujsjekqZj0iFpWLeNA3r88Nzztnkq4F1HTI8n3EnlqtHrcu",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@warenbuchung.de",
                            FirstName = "Admin",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Zwei",
                            Locations = "Lagerort Hamburg, Lagerort Köln",
                            PasswordHash = "$2a$11$u/j1O2ujsjekqZj0iFpWLeNA3r88Nzztnkq4F1HTI8n3EnlqtHrcu",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user3@warenbuchung.de",
                            FirstName = "User",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "Drei",
                            Locations = "Lagerort Köln",
                            PasswordHash = "$2a$11$u/j1O2ujsjekqZj0iFpWLeNA3r88Nzztnkq4F1HTI8n3EnlqtHrcu",
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Warenausgang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribut")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Begruendung")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Customer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Warenausgaenge");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.WarenausgangReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OrderIndex");

                    b.ToTable("WarenausgangReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Kommission",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Auftrag",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Umbuchung",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Beschädigung",
                            OrderIndex = 4
                        });
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Wareneingang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Erfassungstyp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referenz")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Wareneingaenge");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Order", b =>
                {
                    b.HasOne("WarenbuchungApi.Models.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.OrderAssignedItem", b =>
                {
                    b.HasOne("WarenbuchungApi.Models.Order", "Order")
                        .WithMany("AssignedItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarenbuchungApi.Models.Product", "Product")
                        .WithMany("OrderAssignedItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.ProjectAssignedItem", b =>
                {
                    b.HasOne("WarenbuchungApi.Models.Product", "Product")
                        .WithMany("ProjectAssignedItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Warenausgang", b =>
                {
                    b.HasOne("WarenbuchungApi.Models.Product", "Product")
                        .WithMany("Warenausgaenge")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Wareneingang", b =>
                {
                    b.HasOne("WarenbuchungApi.Models.Product", "Product")
                        .WithMany("Wareneingaenge")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Order", b =>
                {
                    b.Navigation("AssignedItems");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Product", b =>
                {
                    b.Navigation("OrderAssignedItems");

                    b.Navigation("ProjectAssignedItems");

                    b.Navigation("Warenausgaenge");

                    b.Navigation("Wareneingaenge");
                });

            modelBuilder.Entity("WarenbuchungApi.Models.Supplier", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
